services:
  drupal:
    # build:
    #   context: .
    image: mass-specc/cms:1.0.0
    ports:
      - 8080:80
    volumes:
      - ./config:/etc/drupal/config
      - ./web/modules:/opt/drupal/web/modules
      - ./web/themes:/opt/drupal/web/themes
      - ./web/sites/default/docker.settings.php:/opt/drupal/web/sites/default/settings.php
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      # - $HOME/.gnupg/pubring.kbx:/var/www/.gnupg/pubring.kbx
      # - $HOME/.gnupg/pubring.kbx~:/var/www/.gnupg/pubring.kbx~
      # - $HOME/.gnupg/private-keys-v1.d:/var/www/.gnupg/private-keys-v1.d
      # - $HOME/.gnupg/random_seed:/var/www/.gnupg/random_seed
      # - $HOME/.gnupg/trustdb.gpg:/var/www/.gnupg/trustdb.gpg
    environment:
      - ADMIN_USERNAME=drupal
      - ADMIN_PASSWORD=drupal
      - HASH_SALT=qD8QuzN0uncuWGdYACnN
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=drupal
      - DB_USERNAME=drupal
      - DB_PASSWORD=drupal
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  postgresql:
    image: bitnamilegacy/postgresql:17.5.0-debian-12-r12
    volumes:
      - "postgresql:/bitnami/postgresql"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=drupal
      - POSTGRESQL_USERNAME=drupal
      - POSTGRESQL_PASSWORD=drupal
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME:-postgres} -d ${POSTGRESQL_DATABASE:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped
volumes:
  postgresql: {}