services:
  drupal:
    build:
      context: .
    ports:
      - 8080:80
    volumes:
      - ./config:/etc/drupal/config
      - ./web/modules:/opt/drupal/web/modules
      - ./web/themes:/opt/drupal/web/themes
      - ./web/sites/default/docker.settings.php:/opt/drupal/web/sites/default/settings.php
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      - ADMIN_USERNAME=drupal
      - ADMIN_PASSWORD=drupal
      - HASH_SALT=qD8QuzN0uncuWGdYACnN
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=drupal
      - DB_USERNAME=drupal
      - DB_PASSWORD=drupal
    depends_on:
      - postgresql

  postgresql:
    image: bitnami/postgresql:17.5.0-debian-12-r12
    volumes:
      - "postgresql:/bitnami/postgresql"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=drupal
      - POSTGRESQL_USERNAME=drupal
      - POSTGRESQL_PASSWORD=drupal
    ports:
      - "5432:5432"

volumes:
  postgresql: {}