version: '3.8'

services:
  drupal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pcdiss-drupal
    ports:
      - "8081:80"
    environment:
      - ADMIN_USERNAME=drupal
      - ADMIN_PASSWORD=drupal
      - HASH_SALT=qD8QuzN0uncuWGdYACnN
      - DB_HOST=postgresql
      - DB_PORT=5432
      - DB_NAME=drupal
      - DB_USERNAME=drupal
      - DB_PASSWORD=drupal
    depends_on:
      - postgresql
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./config:/etc/drupal/config
      - ./web/modules:/opt/drupal/web/modules
      - ./web/themes:/opt/drupal/web/themes
      - ./web/sites/default/docker.settings.php:/opt/drupal/web/sites/default/settings.php
      - ./docker-entrypoint.sh:/docker-entrypoint.sh

  postgresql:
    image: bitnamilegacy/postgresql:17.5.0-debian-12-r12
    container_name: pcdiss-postgresql
    ports:
      - "15433:5432"
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DATABASE=drupal
      - POSTGRESQL_USERNAME=drupal
      - POSTGRESQL_PASSWORD=drupal
    volumes:
      - postgresql:/bitnami/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U drupal -d drupal"]
      interval: 5s
      timeout: 5s
      retries: 12
    restart: unless-stopped

volumes:
  postgresql: {}
