parameters:
  security.enable_super_user: true
  session.storage.options:
    gc_probability: 1
    gc_divisor: 100
    gc_maxlifetime: 200000
    cookie_lifetime: 2000000
    cookie_samesite: Lax
    name_suffix: ""
  twig.config:
    debug: true
    auto_reload: true
    cache: false
    allowed_file_extensions:
      - css
      - html
      - js
      - svg
      - twig
  renderer.config:
    required_cache_contexts:
      ["languages:language_interface", "theme", "user.permissions"]
    auto_placeholder_conditions:
      max-age: 0
      contexts: ["session", "user"]
      tags: []
    debug: false
  http.response.debug_cacheability_headers: false
  factory.keyvalue: {}
  factory.keyvalue.expirable: {}
  filter_protocols:
    - http
    - https
    - ftp
    - news
    - nntp
    - tel
    - telnet
    - mailto
    - irc
    - ssh
    - sftp
    - webcal
    - rtsp
  cors.config:
    enabled: false
    allowedHeaders: []
    allowedMethods: []
    allowedOrigins: ["*"]
    allowedOriginsPatterns: []
    exposedHeaders: false
    maxAge: false
    supportsCredentials: false
  entity.memory_cache.slots: 1000
  queue.config:
    suspendMaximumWait: 30
